Issue 11 documentation
Prepsmith/circleci_webhook_listener pull request #12
Opened 2016-12-07 07:17 UTC by thimovss

2016-12-07 09:17 UTC, rngadam requested changes

2016-12-07 09:17 UTC, rngadam commented on readme.md
>  3.	run "node app.js"
npm start

2016-12-07 09:17 UTC, rngadam commented on readme.md
> +in your circle.yml file write a copy command for all the files that need to be downloaded, to the $CIRCLE_ARTIFACTS directory, after the lines that build your project. For example and android project
extraneous commas

2016-12-07 09:17 UTC, rngadam commented on readme.md
> +TEAM_NAME and PROJECT_NAME can be found when browsing to your project on CircleCI and looking at te url, it should a format like this: "https://circleci.com/gh/{TEAM_NAME}/{PROJECT_NAME}"
te -> the

2016-12-07 09:17 UTC, rngadam commented on readme.md
> +"download_path": "C:\Users\ThimoVSS\circleCIArtifacts"
are you sure these are not supposed to be double backlashes ?

2016-12-07 09:22 UTC, rngadam commented on readme.md
> +This is the port that the webhook listener will listen to, this is the same port that you have to enter in the circle.yml file in the line {yourWebHookAddress}:{thisPort}/webhook
you should change this to not only request for port specification but also the IP to bind to. it's quite common to want to bind specifically to 127.0.0.1:port and then forward traffic to and from using a reverse proxy like nginx. 

as it is: 

. If the hostname is omitted, the server will accept connections on any IPv6 address (::) when IPv6 is available, or any IPv4 address (0.0.0.0) otherwise

https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback

not good if you care about safety.

2016-12-08 04:17 UTC, thimovss commented
All issues should be resolved, will merge when you give me the green-light.

2016-12-08 08:42 UTC, merged